apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: sv-go-test-repo
          artifact-id: debaaf01-65fc-436b-af21-438e927c6d65
          target-environment: aspm_qa
